name: CD-dev
on:
  workflow_dispatch:
  push:
    branches:
      -main

env:
  AZURE_WEBAPP_NAME: ContosoGamingEngineAPI
  SLN_PATH_API: src
  AZURE_WEBAPP_PACKAGE_PATH: Contoso.Gaming.Engine.API/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.ContosoGamingEngineAPI_4ef0 }}
  APPINSIGHTS_CONN: ${{ secrets.APPINSIGHTSCONN }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.100
  WORKING_DIRECTORY: Contoso.Gaming.Engine.API
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    -  name: 'Replace Secrets'
       uses:  microsoft/variable-substitution@v1 
       with:
         files: 'src/Contoso.Gaming.Engine.API/appsettings.json'
       env:
         ApplicationInsights.ConnectionString: ${{ env.APPINSIGHTS_CONN }}

    - name: Install dependencies
      run: dotnet restore ${{ env.SLN_PATH_API }}

    - name: Build
      run: dotnet build ${{ env.SLN_PATH_API }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.SLN_PATH_API }} --no-restore --verbosity normal
      
    - name: dotnet publish
      run: |
        dotnet publish ${{ env.SLN_PATH_API }} -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    #- name: Publish
    #  run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    #- name: Deploy to Azure WebApp
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    #    publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}